version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend-1:
    build: .
    ports:
      - "5010:5010"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5010
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules

  backend-2:
    build: .
    ports:
      - "5011:5010"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=5010
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2

volumes:
  redis-data: